import type { ProviderDefinition, ProviderId } from "./types";

export const providers: ProviderDefinition[] = [
  {
    id: "hostgator",
    label: "HostGator",
    logo: "/logos/hostgator.svg",
    color: "#1d8acb",
    category: "multi",
  },
  {
    id: "godaddy",
    label: "GoDaddy",
    logo: "/logos/godaddy.svg",
    color: "#00a4a6",
    category: "multi",
  },
  {
    id: "hostinger",
    label: "Hostinger",
    logo: "/logos/hostinger.svg",
    color: "#673de6",
    category: "multi",
  },
  {
    id: "siteground",
    label: "SiteGround",
    logo: "/logos/siteground.svg",
    color: "#96cb4c",
    category: "hosting",
  },
  {
    id: "namecheap",
    label: "Namecheap",
    logo: "/logos/namecheap.svg",
    color: "#de3723",
    category: "registrar",
  },
  {
    id: "cloudflare",
    label: "Cloudflare",
    logo: "/logos/cloudflare.svg",
    color: "#f38020",
    category: "multi",
  },
  {
    id: "bluehost",
    label: "Bluehost",
    logo: "/logos/bluehost.svg",
    color: "#196bde",
    category: "hosting",
  },
  {
    id: "ionos",
    label: "IONOS",
    logo: "/logos/ionos.svg",
    color: "#001b41",
    category: "multi",
  },
  {
    id: "wix",
    label: "Wix",
    logo: "/logos/wix.svg",
    color: "#0c6efd",
    category: "multi",
  },
  {
    id: "squarespace",
    label: "Squarespace",
    logo: "/logos/squarespace.svg",
    color: "#111111",
    category: "multi",
  },
  {
    id: "wordpress",
    label: "WordPress",
    logo: "/logos/wordpress.svg",
    color: "#21759b",
    category: "cms",
  },
  {
    id: "cpanel",
    label: "cPanel",
    logo: "/logos/cpanel.svg",
    color: "#ff6c2c",
    category: "panel",
  },
  {
    id: "kinsta",
    label: "Kinsta",
    logo: "/logos/kinsta.svg",
    color: "#5333ed",
    category: "hosting",
  },
  {
    id: "digitalocean",
    label: "DigitalOcean",
    logo: "/logos/digitalocean.svg",
    color: "#0080ff",
    category: "hosting",
  },
  {
    id: "aws",
    label: "AWS",
    logo: "/logos/aws.svg",
    color: "#ff9900",
    category: "hosting",
  },
  {
    id: "shopify",
    label: "Shopify",
    logo: "/logos/shopify.svg",
    color: "#7ab55c",
    category: "multi",
  },
  {
    id: "webflow",
    label: "Webflow",
    logo: "/logos/webflow.svg",
    color: "#146ef5",
    category: "multi",
  },
  {
    id: "vercel",
    label: "Vercel",
    logo: "/logos/vercel.svg",
    color: "#000000",
    category: "hosting",
  },
  {
    id: "netlify",
    label: "Netlify",
    logo: "/logos/netlify.svg",
    color: "#00c7b7",
    category: "hosting",
  },
  {
    id: "render",
    label: "Render",
    logo: "/logos/render.svg",
    color: "#46e3b7",
    category: "hosting",
  },
  {
    id: "firebase",
    label: "Firebase",
    logo: "/logos/firebase.svg",
    color: "#ffca28",
    category: "hosting",
  },
  {
    id: "other",
    label: "Otro",
    color: "#10131a",
    category: "multi",
  },
];

export const getProvider = (id: ProviderId) =>
  providers.find((provider) => provider.id === id) ?? providers[providers.length - 1];
